source "https://rubygems.org"


gem "rails", "~> 8.0.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
gem 'devise'
gem 'devise-jwt'
gem 'pundit'
gem 'jsonapi-serializer'
gem 'dotenv-rails', groups: [:development, :test]
gem 'rack-cors'


group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

# group :production do
#   gem "rack-timeout"
# end
